#!/bin/bash

### BEGIN INIT INFO
# Provides:        liferay62
# Required-Start:  mysql $network
# Required-Stop:   $network
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: Start/Stop Liferay 6.2 server
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

start() {
 /bin/su - liferay -c /home/liferay/liferay/liferay62/tomcat/bin/startup.sh
}

stop() {
 /bin/su - liferay -c /home/liferay/liferay/liferay62/tomcat/bin/shutdown.sh
}

case $1 in
  start|stop) $1;;
  restart) stop; start;;
  *) echo "Run as $0 <start|stop|restart>"; exit 1;;
esac
